global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "chat-backend"
    static_configs:
      - targets: ["backend-service:3000"]
        labels:
          app: "chat-backend"

  - job_name: "mysql-exporter"
    static_configs:
      - targets: ["mysql_exporter:9104"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginxlog-exporter:4040"]

  - job_name: 'telegraf-docker'
    static_configs:
      - targets: ['telegraf:9273']
    scrape_interval: 10s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s